### ISSUE TITLE
[BUG]ERROR - No columns to parse from file

### ISSUE THREAD

**Issue by Zifeng-L** [aertslab/pySCENIC#252] opened 2021-02-03 14:50 UTC
**Describe the bug**
I tried the methods in https://github.com/aertslab/pySCENIC/issues/198#issue-676536487 to create another environment for pyscenic ctx, but it seemed that it still did not work.
```
/sibcb1/mxqianlab1/common/anaconda/envs/pyscenic_ctx/lib/python3.6/site-packages/numba/np/ufunc/parallel.py:355: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9105. The TBB threading layer is disabled.
  warnings.warn(problem)

2021-02-03 22:23:42,933 - pyscenic.cli.pyscenic - INFO - Creating modules.

2021-02-03 22:23:46,701 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-02-03 22:23:56,116 - pyscenic.cli.pyscenic - ERROR - 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)
/sibcb1/mxqianlab1/common/anaconda/envs/pyscenic_ctx/lib/python3.6/site-packages/numba/np/ufunc/parallel.py:355: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9105. The TBB threading layer is disabled.
  warnings.warn(problem)

2021-02-03 22:24:02,529 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-02-03 22:25:54,443 - pyscenic.cli.pyscenic - INFO - Loading gene signatures.

2021-02-03 22:25:54,444 - pyscenic.cli.pyscenic - ERROR - No columns to parse from file
```

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```
pyscenic ctx \
    $grn_output \
    $f_db_names \
    --annotations_fname $f_motif_path \
    --expression_mtx_fname $f_loom_path_scenic \
    --output $ctx_output \
    --num_workers 20
```

**Please complete the following information:**
- pySCENIC version: 0.10.4
- Installation method: Pip
- Run environment: CLI
- OS: Linux
- Package versions:
- arboreto==0.1.5
attrs==20.3.0
boltons==20.2.1
cached-property==1.5.2
certifi==2016.2.28
click==7.1.2
cloudpickle==1.6.0
cytoolz==0.11.0
dask==2021.1.1
decorator==4.4.2
dill==0.3.3
distributed==1.28.1
frozendict==1.2
fsspec==0.8.5
h5py==3.1.0
HeapDict==1.0.1
interlap==0.2.7
joblib==1.0.0
llvmlite==0.33.0
locket==0.2.1
loompy==3.0.6
msgpack==1.0.2
multiprocessing-on-dill==3.5.0a4
networkx==2.5
numba==0.50.0
numpy==1.19.5
numpy-groupies==0.9.13
pandas==1.1.5
partd==1.1.0
psutil==5.8.0
pyarrow==0.16.0
pynndescent==0.5.1
pyscenic==0.10.4
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
scikit-learn==0.24.1
scipy==1.5.4
six==1.15.0
sortedcontainers==2.3.0
tblib==1.7.0
threadpoolctl==2.1.0
toolz==0.11.1
tornado==6.1
tqdm==4.56.0
umap-learn==0.5.0
zict==2.0.0

```
...
```

**Comment by cflerin** [comment] 2021-02-03 18:36
Hi @Zifeng1995 ,

Possibly a similar issue to #245 , could you try downgrading numba?

```
pip install numba==0.46.0
```

**Comment by lucygarner** [comment] 2021-08-09 17:54
I have this issue with pyscenic 0.11.2 as well.  Would you suggest downgrading numba again?

**Comment by ghuls** [comment] 2021-08-10 09:47
@lucygarner I think the problem is with one of your input files (which contains non ASCII characters).
Can you run `file <filename>` for each input file? It should return `ASCII text` for each text input file, but I suspect that one file will be in UTF-8 format (e.g. a gene name with greek symbols).

```
file ${input_files}
```

**Comment by lucygarner** [comment] 2021-08-10 13:00
They come back as `ASCII text` so I don't think that's the problem.  See my new issue #316.

**Closed** 2021-12-03 08:04 UTC
Labels: bug
