### ISSUE TITLE
very useful on 2020-4-18

### ISSUE THREAD

**Issue by millersan** [aertslab/pySCENIC#156] opened 2020-04-18 12:33 UTC
I used the following installation steps.

pip install pyscenic

Got errors in running grnboost2 as above,did the following install/upgrades

python -m pip install 'fsspec>=0.3.3
python -m pip install dask[dataframe] --upgrade
pip install distributed -U

which fixed the issue.

python3.6.3 on IBM LSF HPC cluster.

`dask==2.11.0`
`pyscenic==0.10.0`
`distributed==2.11.0`

_Originally posted by @smanne07 in https://github.com/aertslab/pySCENIC/issues/147#issuecomment-597686104_

**Comment by cflerin** [comment] 2020-05-18 15:16
Closing as a duplicate of #147

**Closed by cflerin** 2020-05-18 15:16 UTC
