### ISSUE TITLE
pySCENIC stuck at prune2df

### ISSUE THREAD

**Issue by lc822** [aertslab/pySCENIC#104] opened 2019-10-28 10:24 UTC
Hi,

I am trying to run pySCENIC in a Jupyter notebook following the tutorial, however it keeps getting stuck at the following stage.

`with ProgressBar():
    df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME)`

The progress bar remains at 0% even after 206 hr.  I am using a shared server space and the server manager told me that there is a limit on each system for how many running processes I can have at once, and I seem to be reaching this when running pySCENIC.

Do you have any suggestions as to what might be going wrong?  Sorry, I am quite new to Python.

Many thanks,
Lucy

**Comment by kunUCSD** [comment] 2019-10-30 16:53
Hi there,

I got the same problem when running in Jupyter...
I tried to use multiprocessing, and it kept zero status.
Not sure if this error can help to find the issue:
"distributed.core - INFO - Event loop was unresponsive in Nanny for 26.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability."

Best, K

**Comment by bramvds** [comment] 2019-10-31 08:13
Dear Lucy, Dear K,

Does this issue also appear when using the command line interface (CLI)? The choice between the dask multiprocessing scheduler or a custom implementation that does not depend on dask is controlled via the argument `--mode=dask_multiprocessing` (default) versus `--mode=custom_multiprocessing`. These implementations are very different and hopefully one of these will run on your hardware.

Which versions of dask and pandas do you use?

Kindest regards,
Bram

**Comment by lc822** [comment] 2019-10-31 11:07
Dear Bram,

The command line interface seemed to work ok for me.  I am using the dask_multiprocessing mode.  

dask 1.0.0 and pandas 0.25.1

Best wishes,
Lucy

**Comment by kunUCSD** [comment] 2019-10-31 17:56
Hi Bram,

Thanks for your reply. I used custom_multiprocessing and stuck there. With your tips, dask_multiprocessing at least have some progress, but seems stuck again. Any other suggestions? Thanks
I used dask 1.2.2, pandas 0.25.1


[                                        ] | 0% Completed | 30.1s

2019-10-31 10:38:34,066 - pyscenic.transform - WARNING - Less than 80% of the genes in Sim1 could be mapped to mm9-500bp-upstream-7species.mc9nr. Skipping this module.


[                                        ] | 0% Completed | 30.2s

2019-10-31 10:38:34,229 - pyscenic.transform - WARNING - Less than 80% of the genes in Six4 could be mapped to mm9-500bp-upstream-7species.mc9nr. Skipping this module.


[                                        ] | 0% Completed | 30.4s

2019-10-31 10:38:34,378 - pyscenic.transform - WARNING - Less than 80% of the genes in Six6 could be mapped to mm9-500bp-upstream-7species.mc9nr. Skipping this module.


[                                        ] | 0% Completed | 33.6s

2019-10-31 10:38:37,522 - pyscenic.transform - WARNING - Less than 80% of the genes in Neurog2 could be mapped to mm9-500bp-upstream-7species.mc9nr. Skipping this module.


[                                        ] | 0% Completed | 36min 58.1s

Best, Kun


________________________________

**Comment by Sophia409** [comment] 2019-12-08 15:03
@lc822 @kunUCSD @bramvds Hi,how did you solve this problem? I have the same question.The progress bar remains at 0%. After I change client_or_address to 'custom_multiprocessing', it shows that  pyscenic.prune - INFO - Using 12 workers and gives no progress bar or any another output.
Is my way of changing mode wrong? 
I'm running it in jupyter notebook. Can you give me some advice?
```
with ProgressBar():
    df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME,num_workers=12)
[                                        ] | 0% Completed |  10min 45.0s
```
```
# Calculate a list of enriched motifs and the corresponding target genes for all modules.
with ProgressBar():
    df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME,num_workers=12,client_or_address='custom_multiprocessing')
2019-12-08 22:57:46,651 - pyscenic.prune - INFO - Using 12 workers.

2019-12-08 22:57:46,651 - pyscenic.prune - INFO - Using 12 workers.
```

**Comment by lc822** [comment] 2019-12-18 10:18
Hi @Sophia409,

I didn't manage to solve this problem in the end - I had to switch to the command line version.

Best,
Lucy

**Comment by Sophia409** [comment] 2019-12-18 10:59
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you, I also switched to CLI.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yuhongruoyi
                            
                    
                        
                            
                                    yuhongruoyi@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 12/18/2019 18:18，Lucy G<notifications@github.com> wrote： 


Hi @Sophia409,
I didn't manage to solve this problem in the end - I had to switch to the command line version.
Best,
Lucy

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ureyandy2009** [comment] 2020-07-03 09:22
Hello, everyone. 

Although i still have many questions about the downstream analysis, it seems that i have solved this problem in GRN and prune2df. First, errors occurred  when i used the SCENIC for R in windows in the step runSCENIC_2_creatRegulons. So i used python instead. However, errors still occurred when i run grnboosts2 in pyscenic on windows10. So i used pyscenic on linux. Then the problem you mentioned in prune2df occurred. 
    In my case (24 processors with 4.2GHZ and 64G RAM), one feather costs about 40G RAM, so the computer shut down when i used 2 feathers at the same time. And this problem was solved when i used only one feather.
    I wish these messages would be helpful.

yours,
andy

**Comment by cflerin** [comment] 2020-07-07 09:17
Thanks for sharing your experience, @ureyandy2009 .

I'm going to close this as a duplicate since there is more information in #142, which can stay open until this is resolved.

**Closed by cflerin** 2020-07-07 09:17 UTC
Labels: bug
